#!/bin/bash
. ./examples/ade20k/train/plot.sh 0 caffenet
. ./examples/ade20k/train/plot.sh 1 caffenet
. ./examples/ade20k/train/plot.sh 2 caffenet
. ./examples/ade20k/train/plot.sh 3 caffenet
. ./examples/ade20k/train/plot.sh 4 caffenet
. ./examples/ade20k/train/plot.sh 5 caffenet
. ./examples/ade20k/train/plot.sh 6 caffenet
. ./examples/ade20k/train/plot.sh 7 caffenet
. ./examples/ade20k/train/plot.sh 0 alexnet
. ./examples/ade20k/train/plot.sh 1 alexnet
. ./examples/ade20k/train/plot.sh 2 alexnet
. ./examples/ade20k/train/plot.sh 3 alexnet
. ./examples/ade20k/train/plot.sh 4 alexnet
. ./examples/ade20k/train/plot.sh 5 alexnet
. ./examples/ade20k/train/plot.sh 6 alexnet
. ./examples/ade20k/train/plot.sh 7 alexnet
. ./examples/ade20k/train/plot.sh 0 googlenet
. ./examples/ade20k/train/plot.sh 1 googlenet
. ./examples/ade20k/train/plot.sh 2 googlenet
. ./examples/ade20k/train/plot.sh 3 googlenet
. ./examples/ade20k/train/plot.sh 4 googlenet
. ./examples/ade20k/train/plot.sh 5 googlenet
. ./examples/ade20k/train/plot.sh 6 googlenet
. ./examples/ade20k/train/plot.sh 7 googlenet
. ./examples/ade20k/train/plot.sh 0 vgg16
. ./examples/ade20k/train/plot.sh 1 vgg16
. ./examples/ade20k/train/plot.sh 2 vgg16
. ./examples/ade20k/train/plot.sh 3 vgg16
. ./examples/ade20k/train/plot.sh 4 vgg16
. ./examples/ade20k/train/plot.sh 5 vgg16
. ./examples/ade20k/train/plot.sh 6 vgg16
. ./examples/ade20k/train/plot.sh 7 vgg16
. ./examples/ade20k/train/plot.sh 0 resnet50
. ./examples/ade20k/train/plot.sh 1 resnet50
. ./examples/ade20k/train/plot.sh 2 resnet50
. ./examples/ade20k/train/plot.sh 3 resnet50
. ./examples/ade20k/train/plot.sh 4 resnet50
. ./examples/ade20k/train/plot.sh 5 resnet50
. ./examples/ade20k/train/plot.sh 6 resnet50
. ./examples/ade20k/train/plot.sh 7 resnet50
